### ISSUE TITLE
Messages don't open

### ISSUE THREAD

**Issue by Dodge100** [Nonexistent-Name/gradevue#8]
In the messages tab, messages don't open.

**Comment by Nonexistent-Name** [comment]
Synergy's API doesn't provide message content, as far as I'm aware. If anyone's found a way to access message content, I will add this feature.

**Comment by thiccaxe** [comment]
it might be possible. We can use an api endpoint to generate an auth token and then open an Iframe on the -psv.edupoint  at the message url. maybe

**Comment by thiccaxe** [comment]
I updated the app and it has new API for this!
